### ISSUE TITLE
[Bug] Connect / disconnect delay

### ISSUE THREAD

**Issue by uniquenode** [zoli/nordtray#4]
Hello,

Thank you for creating this package, this is exactly what I was searching for, and even better, there is an AUR package!

When connecting and disconnecting it takes like 50 seconds before the state change is detected and the icon stops changing, whilst nordvpn status detects it instantly. I believe there is something wrong with the output parsing.

Please find below the outputs of nordvpn:

```
 arch% nordvpn status
 Status: Connected
 Current server: nl894.nordvpn.com
 Country: Netherlands
 City: Amsterdam
 Server IP: 213.232.87.119
 Current technology: NORDLYNX
 Current protocol: UDP
 Transfer: 15.54 KiB received, 21.25 KiB sent
 Uptime: 9 seconds
```

```
 arch% nordvpn settings
 Technology: NORDLYNX
 Firewall: enabled
 Kill Switch: disabled
 CyberSec: disabled
 Notify: disabled
 Auto-connect: disabled
 IPv6: disabled
 DNS: disabled
```

**Comment by zoli** [comment]
Hi, You're Welcome.
> When connecting and disconnecting it takes like 50 seconds before the state change is detected and the icon stops changing, whilst nordvpn status detects it instantly.

connecting and disconnecting using the tray icon or the nordvpn cli?

**Comment by uniquenode** [comment]
> Hi, You're Welcome.
> > When connecting and disconnecting it takes like 50 seconds before the state change is detected and the icon stops changing, whilst nordvpn status detects it instantly.
> 
> connecting and disconnecting using the tray icon or the nordvpn cli?
> 

When connecting from the tray, the icon starts flashing and it takes 50 seconds for it to stop and the menu to show the disconnect item, i.e. for it to detect the state change. The cli shows it connects almost instantly.

**Comment by uniquenode** [comment]
This issue was caused by the `nordvpn connect` and `nordvpn disconnect` commands not exiting due to a dbus permission issue that got triggered by the notifications functionality of nordvpn. So it had nothing to do with this project.
